
# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.

name: criptografia
version: '0.0.0'
license: MIT
maintainer: Juan Bono
github: juanbono/criptografia
synopsis: Cryptographic Algorithms
description: Cryptographic Algorithms
category: Other

dependencies:
  - bytestring
  - largeword
  - lens
  - modular-arithmetic
  - vector

library:
  dependencies:
  - base
  - split
  - vector-sized
  source-dirs: library
  exposed-modules:
    - Criptografia
  ghc-options:
    - -O2
    - -Wall

executables:
  mugi:
    dependencies:
    - base
    - criptografia
    - optparse-applicative
    ghc-options:
    - -rtsopts
    main: Main.hs
    source-dirs: executable-cli
  cripto-gui:
    dependencies:
      - base
      - criptografia
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable-gui

tests:
  criptografia-test-suite:
    dependencies:
    - base
    - criptografia
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - tasty-hunit
    - tasty-discover
    - bytestring-arbitrary
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  criptografia-benchmarks:
    dependencies:
    - base
    - criptografia
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
