flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- modular-arithmetic-1.2.1.2
- bytestring-arbitrary-0.1.1

resolver: lts-9.11

build:
  library-profiling: false
  executable-profiling: false
